ktor:
  deployment:
    port: 9260
  application:
    modules:
      - galaGuide.MainKt.init
user-jwt:
  secret: 1145141919810
  issuer: localhost
  audience: localhost/user
  realm: 'Access to user'
user:
  email-verify:
    host: localhost
    port: 9260
    username: 111
    password: 222
    title: 'Galaguide Email Verification'
    sender: ''
    sender-email: ''
    template: 'Welcome to Galaguide! Your email verification code is: %s'
    request-interval: 60
    expire-time: 3600